// Banco de palabras por país
// Cada palabra tiene una "pista" relacionada pero distinta, que es lo que ven los impostores
const WORD_BANKS = {
  chile: [
    { palabra: "Guagua", pista: "Bebé" },
    { palabra: "Carrete", pista: "Fiesta" },
    { palabra: "Pega", pista: "Trabajo" },
    { palabra: "Once", pista: "Comida de la tarde" },
    { palabra: "Pololo", pista: "Pareja" },
    { palabra: "Fome", pista: "Aburrido" },
    { palabra: "Cahuín", pista: "Chisme" },
    { palabra: "Tincazo", pista: "Presentimiento" },
    { palabra: "Pituto", pista: "Contacto/favor" },
    { palabra: "Bacán", pista: "Genial" },
    { palabra: "Lolo", pista: "Adolescente" },
    { palabra: "Caña", pista: "Resaca" },
    { palabra: "Achaplinado", pista: "Tímido" },
    { palabra: "Pucho", pista: "Cigarro" },
    { palabra: "Al lote", pista: "Desordenado" },
    { palabra: "Choro", pista: "Valiente" },
    { palabra: "Funa", pista: "Escándalo público" },
    { palabra: "Yapa", pista: "Extra gratis" },
    { palabra: "Sopaipilla", pista: "Comida frita" },
    { palabra: "Completo", pista: "Hot dog" }
  ],
  mexico: [
    { palabra: "Chamba", pista: "Trabajo" },
    { palabra: "Chido", pista: "Genial" },
    { palabra: "Antro", pista: "Discoteca" },
    { palabra: "Camión", pista: "Autobús" },
    { palabra: "Chela", pista: "Cerveza" },
    { palabra: "Neta", pista: "Verdad" },
    { palabra: "Chamaco", pista: "Niño" },
    { palabra: "Cruda", pista: "Resaca" },
    { palabra: "Fresa", pista: "Persona presumida" },
    { palabra: "Padrísimo", pista: "Excelente" },
    { palabra: "Wey", pista: "Amigo" },
    { palabra: "Chafa", pista: "Mala calidad" },
    { palabra: "Mande", pista: "¿Cómo dijiste?" },
    { palabra: "Chamba", pista: "Empleo" },
    { palabra: "Torta", pista: "Sándwich" },
    { palabra: "Naco", pista: "De mal gusto" },
    { palabra: "Chavo", pista: "Joven" },
    { palabra: "Órale", pista: "Expresión de sorpresa" },
    { palabra: "Pinche", pista: "Maldito" },
    { palabra: "Refresco", pista: "Gaseosa" }
  ],
  argentina: [
    { palabra: "Boludo", pista: "Amigo/tonto" },
    { palabra: "Mate", pista: "Infusión" },
    { palabra: "Quilombo", pista: "Desorden" },
    { palabra: "Laburo", pista: "Trabajo" },
    { palabra: "Pibe", pista: "Chico" },
    { palabra: "Bondi", pista: "Autobús" },
    { palabra: "Che", pista: "Expresión para llamar atención" },
    { palabra: "Trucho", pista: "Falso" },
    { palabra: "Buena onda", pista: "Persona agradable" },
    { palabra: "Bárbaro", pista: "Genial" },
    { palabra: "Chamuyo", pista: "Palabrería" },
    { palabra: "Posta", pista: "En serio" },
    { palabra: "Garrón", pista: "Mala suerte" },
    { palabra: "Morfar", pista: "Comer" },
    { palabra: "Facha", pista: "Apariencia atractiva" },
    { palabra: "Birra", pista: "Cerveza" },
    { palabra: "Fiaca", pista: "Pereza" },
    { palabra: "Gamba", pista: "Cien pesos" },
    { palabra: "Choripán", pista: "Comida con pan y chorizo" },
    { palabra: "Curro", pista: "Estafa" }
  ],
  colombia: [
    { palabra: "Parce", pista: "Amigo" },
    { palabra: "Chévere", pista: "Genial" },
    { palabra: "Berraco", pista: "Persona capaz" },
    { palabra: "Bacano", pista: "Agradable" },
    { palabra: "Guayabo", pista: "Resaca" },
    { palabra: "Rumba", pista: "Fiesta" },
    { palabra: "Camello", pista: "Trabajo" },
    { palabra: "Tinto", pista: "Café negro" },
    { palabra: "Gonorrea", pista: "Insulto fuerte" },
    { palabra: "Vaina", pista: "Cosa" },
    { palabra: "Llave", pista: "Amigo cercano" },
    { palabra: "Parche", pista: "Plan/reunión" },
    { palabra: "Man", pista: "Persona" },
    { palabra: "Mecato", pista: "Snacks" },
    { palabra: "Carecoche", pista: "Persona sin vehículo" },
    { palabra: "Chimba", pista: "Algo genial" },
    { palabra: "Polas", pista: "Cervezas" },
    { palabra: "Verraquera", pista: "Cosa impresionante" },
    { palabra: "Cantaleta", pista: "Regaño repetitivo" },
    { palabra: "Arepa", pista: "Comida de maíz" }
  ],
  venezuela: [
    { palabra: "Pana", pista: "Amigo" },
    { palabra: "Chamo", pista: "Joven" },
    { palabra: "Arrecho", pista: "Molesto/genial (según contexto)" },
    { palabra: "Bochinche", pista: "Desorden/chisme" },
    { palabra: "Cotufa", pista: "Palomitas de maíz" },
    { palabra: "Cuaima", pista: "Persona celosa" },
    { palabra: "Jeva", pista: "Novia" },
    { palabra: "Ladilla", pista: "Fastidioso" },
    { palabra: "Cónchale", pista: "Expresión de sorpresa" },
    { palabra: "Burda", pista: "Mucho/demasiado" },
    { palabra: "Catira", pista: "Mujer rubia" },
    { palabra: "Guachimán", pista: "Vigilante" },
    { palabra: "Chévere", pista: "Genial" },
    { palabra: "Fino", pista: "Está bien" },
    { palabra: "Mamadera de gallo", pista: "Burla/broma" },
    { palabra: "Echarle pichón", pista: "Esforzarse" },
    { palabra: "Bicha", pista: "Mujer atractiva" },
    { palabra: "Zumbado", pista: "Loco/atrevido" },
    { palabra: "Arepa", pista: "Comida de maíz" },
    { palabra: "Birra", pista: "Cerveza" }
  ]
};

const COUNTRY_NAMES = {
  chile: "Chile",
  mexico: "México",
  argentina: "Argentina",
  colombia: "Colombia",
  venezuela: "Venezuela"
};
